# Generated by Django 4.1.7 on 2023-02-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_number', models.CharField(max_length=10)),
                ('to_number', models.CharField(max_length=10)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
